-- CreateTable
CREATE TABLE "tbl_seo_settings" (
    "id" SERIAL NOT NULL,
    "site_name" TEXT,
    "site_name_short" TEXT,
    "site_url" TEXT,
    "locale" TEXT,
    "default_title" TEXT,
    "default_description" TEXT,
    "keywords" TEXT,
    "og_image" TEXT,
    "church_name" TEXT,
    "church_alternate_name" TEXT,
    "church_description" TEXT,
    "telephone" TEXT,
    "whatsapp" TEXT,
    "street_address" TEXT,
    "address_locality" TEXT,
    "address_region" TEXT,
    "postal_code" TEXT,
    "address_country" TEXT,
    "service_name" TEXT,
    "day_of_week" TEXT,
    "opens" TEXT,
    "closes" TEXT,
    "instagram" TEXT,
    "facebook" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tbl_seo_settings_pkey" PRIMARY KEY ("id")
);

-- Seed data awal SEO (nilai default konfigurasi GBI PLC)
INSERT INTO "tbl_seo_settings" (
    "id",
    "site_name",
    "site_name_short",
    "site_url",
    "locale",
    "default_title",
    "default_description",
    "keywords",
    "og_image",
    "church_name",
    "church_alternate_name",
    "church_description",
    "telephone",
    "whatsapp",
    "street_address",
    "address_locality",
    "address_region",
    "postal_code",
    "address_country",
    "service_name",
    "day_of_week",
    "opens",
    "closes",
    "instagram",
    "facebook",
    "created_at",
    "updated_at"
) VALUES (
    1,
    'GBI Philadelphia Life Center',
    'GBI PLC',
    'https://philadelphialifecenter.com',
    'id_ID',
    'GBI Philadelphia Life Center — Gereja di Yogyakarta',
    'GBI Philadelphia Life Center (GBI PLC) adalah gereja Bethel di Yogyakarta. Ibadah Raya setiap Minggu pukul 10.00 WIB, Saat Teduh harian, materi kotbah, Youth Ministry, dan Life Group.',
    'gereja, GBI, gereja di jogja, gereja di Yogyakarta, gereja di sleman, kotbah, ibadah raya, materi kotbah, saat teduh, GBI PLC, philadelphia life center',
    NULL,
    'GBI Philadelphia Life Center',
    'GBI PLC',
    'Gereja Bethel Indonesia (GBI) Philadelphia Life Center di Yogyakarta yang melayani Ibadah Raya, Youth Ministry, dan Life Group.',
    '+6285336618852',
    '6285336618852',
    'Jl. Babarsari No.45, Janti, Caturtunggal, Kec. Depok',
    'Sleman',
    'Daerah Istimewa Yogyakarta',
    '55281',
    'ID',
    'Ibadah Raya',
    'Sunday',
    '10:00',
    '12:00',
    '',
    '',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
